# Generated by Django 5.1.7 on 2025-03-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "username",
                    models.CharField(
                        default=None, max_length=100, null=True, verbose_name="用户名"
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        default=None, max_length=32, null=True, verbose_name="密码"
                    ),
                ),
                (
                    "member_type",
                    models.CharField(
                        default="user", max_length=20, null=True, verbose_name="用户类型"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上次登录时间"),
                ),
            ],
            options={
                "verbose_name_plural": "用户表",
                "db_table": "member",
            },
        ),
        migrations.CreateModel(
            name="Token",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "member_id",
                    models.IntegerField(default=None, null=True, verbose_name="用户ID"),
                ),
                (
                    "token_value",
                    models.CharField(
                        default=None, max_length=200, null=True, verbose_name="签发token"
                    ),
                ),
                ("issued_time", models.DateTimeField(auto_now=True)),
                ("expire_time", models.DateTimeField(auto_now_add=True)),
                ("uuid", models.CharField(default=None, max_length=200, null=True)),
            ],
            options={
                "verbose_name_plural": "用户Token",
                "db_table": "token",
            },
        ),
    ]
