# Generated by Django 5.1.7 on 2025-03-26 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("memberManage", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("summary", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="memberManage.member",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "会话表",
                "db_table": "conversation",
            },
        ),
        migrations.CreateModel(
            name="ChatRecord",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("sender", models.CharField(max_length=32)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="messageManage.conversation",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "聊天记录表",
                "db_table": "chat_record",
            },
        ),
    ]
